language: node_js
node_js:
  - 8.4.0

# script: "npm run lint && npm test"
script: "echo \"skipping tests\""

deploy:
  provider: script
  script: bin/deploy_prod.sh
  on:
    # branch: master
    branch: prod_deploy_test
