language: node_js
node_js:
  - 8.4.0

script: "npm run lint && npm test"

deploy:
  skip_cleanup: true
  provider: script
  script: bin/deploy_prod.sh
  on:
    # branch: master
    branch: prod_deploy_test
